sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - main # build master branch only

before_install:               # install 阶段之前执行
  - npm install -g hexo-cli   # 全局安装 Hexo 命令行工具

install:                      # 在安装项目环境阶段需要运行的命令，一条一行，类似的还有 before_install
  - npm install               # 安装 package.json 中的依赖

before_script:
   -wget https://github.com/jgm/pandoc/releases/download/2.10.1/pandoc-2.10.1-1-amd64.deb
   -sudo dpkg -i pandoc-2.10.1-1-amd64.deb
   -npm install hexo-renderer-pandoc --save   ＃ for mathjax 
   -npm安装


script:
  - hexo clean
  - hexo generate # Hexo 常规命令，执行清理和生成

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public

notifications: # 设置通知项
  email: true



